### ISSUE TITLE
Error: Decoded message is not valid

### ISSUE THREAD

**Issue by ralphtheninja** [cabal-club/cabal#19]
```
Error: Decoded message is not valid
    at Object.decode (/home/lms/src/cabal-node/node_modules/hyperdb/lib/messages.js:117:39)
    at Writer._decode (/home/lms/src/cabal-node/node_modules/hyperdb/index.js:756:28)
    at Request._callback (/home/lms/src/cabal-node/node_modules/hyperdb/index.js:785:10)
    at Request.callback (/home/lms/src/cabal-node/node_modules/random-access-storage/index.js:152:8)
    at onread (/home/lms/src/cabal-node/node_modules/random-access-file/index.js:80:31)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:569:17)
```

**Comment by ralphtheninja** [comment]
Works when pulling latest and reinstalling deps.
